[package]
name = "court-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true

reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] }
thiserror = "2"
